spring:
  main:
    web-application-type: NONE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    io.dsub: DEBUG
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false