spring:
  main:
    web-application-type: NONE
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    io.dsub: DEBUG
#    org.springframework: DEBUG
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
